run:
  build-tags:
    - build
  timeout: 10m

linters:
  enable:
    - errcheck
    - goimports
    - gofmt
    - gosec
    - gocritic
    - deadcode
    - misspell
    # replacement to golint, but it seems to be very verbose
    # this is why it's commented but the old one is removed
    #- revive
